### ISSUE TITLE
weights help

### ISSUE THREAD

**Issue by LuanTran07** [vibhorkrishna/S.H.A.D.Y#5]
configPath = "./cfg/yolov4-tiny.cfg"                                 # Path to cfg
weightPath = "./yolov4-tiny.weights"                               # Path to weights
metaPath = "./cfg/coco.data"                                         # Path to meta data

Could you share the .weights and .cfg of the fall detection?
Thank you very much!

**Comment by vibhorkrishna** [comment]
You must have downloaded the darknet folder from this GitHub: [Darknet](https://github.com/AlexeyAB/darknet)
You will get the cfg and coco file from the cfg folder.
For Yolo weights check the GitHub. Under the heading "Pre-Trained Models", you will get different types of weight files. Download accordingly. 
Most commonly used weights file: [Tiny Yolo4 Weight](https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights) and [Yolo4 Weight](https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights)
There are no specific files for fall detection. Yolo weights and cfg are universal.
Only code is different for fall detection.
