### ISSUE TITLE
raise ValueError("Invalid config path `" +

### ISSUE THREAD

**Issue by Eddielw** [vibhorkrishna/S.H.A.D.Y#6]
(base) C:\Users\C2-COMPUTER>cd C:\Users\C2-COMPUTER\Desktop\yolo fall detection vibhorkrishna\darknet-master\build\darknet\x64\S.H.A.D.Y-main\Deployed App

(base) C:\Users\C2-COMPUTER\Desktop\yolo fall detection vibhorkrishna\darknet-master\build\darknet\x64\S.H.A.D.Y-main\Deployed App>python app.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with watchdog (windowsapi)
 * Debugger is active!
 * Debugger PIN: 613-382-091
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [10/Sep/2022 23:19:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2022 23:19:37] "GET /FallDetection HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2022 23:19:37] "GET /assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css')%7D%7D HTTP/1.1" 404 -
127.0.0.1 - - [10/Sep/2022 23:19:37] "GET /static/assets/css/util.css HTTP/1.1" 404 -
127.0.0.1 - - [10/Sep/2022 23:19:45] "POST /Video HTTP/1.1" 200 -
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "C:\Users\C2-COMPUTER\anaconda3\Lib\site-packages\werkzeug\wsgi.py", line 462, in __next__
    return self._next()
  File "C:\Users\C2-COMPUTER\anaconda3\Lib\site-packages\werkzeug\wrappers\response.py", line 50, in _iter_encoded
    for item in iterable:
  File "C:\Users\C2-COMPUTER\Desktop\yolo fall detection vibhorkrishna\darknet-master\build\darknet\x64\S.H.A.D.Y-main\Deployed App\app.py", line 318, in gen_frames
    raise ValueError("Invalid config path `" +
ValueError: Invalid config path `C:\Users\C2-COMPUTER\Desktop\yolo fall detection vibhorkrishna\darknet-master\build\darknet\x64\S.H.A.D.Y-main\Deployed App\cfg\yolov4-tiny.cfg`
127.0.0.1 - - [10/Sep/2022 23:19:45] "GET /video_feed HTTP/1.1" 200 -

**Comment by Dhyyeyyy** [comment]
did you find solution?

**Comment by prathik-codoc** [comment]
You need to install the YoloV4 and openCV for that. Follow the tutorials from this video: https://youtu.be/5pYh1rFnNZs?si=YLlbmbuYqfITYaer
