### ISSUE TITLE
Person sleeping 

### ISSUE THREAD

**Issue by ghost** [vibhorkrishna/S.H.A.D.Y#8]
In fall detection project you mentioned that when height is greater than the width and vice versa you detect if person is fall down or not but what about when person is sleeping ? How you deal with that condition ?

**Comment by vibhorkrishna** [comment]
Yeah, fall detection will not work on a sleeping person. The solution could be to check whether the person is lying on the bed or not. If the person is on a bed then that will not be considered as a fall.
